services:
  orchestrator:
    #build: .
    image: ghcr.io/boecks/stardew-multiplayer-docker-orchestrator:latest
    container_name: stardew-orchestrator
    network_mode: "host"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
